const BingoDataJson = [
    { 'Id': 1, 'Text': 'Tu mamá te consintió (caricias, comida, palabras bonitas, etc.)', 'Active': 0 },
    { 'Id': 2, 'Text': 'Leer para viajar a otras vidas', 'Active': 0 },
    { 'Id': 3, 'Text': 'Josué o Sergio conversaron contigo', 'Active': 0 },
    { 'Id': 4, 'Text': 'Tu hermana bromeó/molestó a tu mamá', 'Active': 0 },
    { 'Id': 5, 'Text': 'Un perrito que no conoces se acercó a ti', 'Active': 0 },
    { 'Id': 6, 'Text': 'Hacer hamas con tu pareja', 'Active': 0 },
    { 'Id': 7, 'Text': 'Algún familiar (fuera de tu casa) te escribió', 'Active': 0 },
    { 'Id': 8, 'Text': 'Salir a cantar', 'Active': 0 },
    { 'Id': 9, 'Text': 'Meditar. Te ayudará a transitar y conectar con el universo', 'Active': 0 },
    { 'Id': 10, 'Text': 'Pasó algo chistoso en clase (cualquiera de las que tomas)', 'Active': 0 },
    { 'Id': 11, 'Text': 'Cambiarle el nombre a alguien durante 2 minutos', 'Active': 0 },
    { 'Id': 12, 'Text': 'Ganar una guerra de pulgares a tu pareja', 'Active': 0 },
    { 'Id': 13, 'Text': 'Un niño te hizo sentir ternura', 'Active': 0 },
    { 'Id': 14, 'Text': 'Ver una peli con tu pareja', 'Active': 0 },
    { 'Id': 15, 'Text': 'Escuchaste en la calle una canción que disfrutas mucho', 'Active': 0 },
    { 'Id': 16, 'Text': 'Ver la Luna', 'Active': 0 },
    { 'Id': 17, 'Text': 'Saltar lo más alto 10 veces seguidas', 'Active': 0 },
    { 'Id': 18, 'Text': 'Compartiste con tu familia una Salida', 'Active': 0 },
    { 'Id': 19, 'Text': 'Tu pareja te hizo reír fuerte', 'Active': 0 },
    { 'Id': 20, 'Text': 'Dar una voltereta o medialuna', 'Active': 0 },
    { 'Id': 21, 'Text': 'Decirle un cumplido a 3 personas (conocidas o desconocidas)', 'Active': 0 },
    { 'Id': 22, 'Text': 'Conectar con la magía del yoga', 'Active': 0 },
    { 'Id': 23, 'Text': 'Tocar la cabeza a 5 personas diferentes dentro de 30 minutos (no puedes decirles por qué)', 'Active': 0 },
    { 'Id': 24, 'Text': 'Tu pareja te preparó algo para desayunar/cenar', 'Active': 0 },
    { 'Id': 25, 'Text': 'Viste a alguien con alguna prenda de vestir color ROJO', 'Active': 0 }
]